# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://lsslss.github.io
date_format: "ordinal"
title: lss 實驗室 beta 2
subtitle: "未能盡如人意，但求無愧於心。"
description: "電腦課教學與一些心得"
keywords: lss, blog
timezone: Asia/Taipei
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: lss
# organization: 
# organization_url: 
github_username: lss
location: Taoyuan, Taiwan
email: lsslss@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首頁

  -
    href: /categories/
    label: 文章分類

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 連結

  -
    href: /about/
    label: 關於我

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# repository: lsslss/lsslss.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
# comments_provider: gitalk
# !!!重要!!! 請修改以下的訊息為你自己申請的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
# disqus:
#    username: 
# https://imsun.net/posts/gitment-introduction/
# gitment:
#    owner: mzlogin
#    repo: blog-comments
#    oauth:
#        client_id: d2e1cbbd298958076462
#        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
# gitalk:
#    owner: mzlogin
#    repo: blog-comments
#    clientID: d2e1cbbd298958076462
#    clientSecret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
# google:
#    analytics_id: UA-80669434-1
